postgres:
  image: postgres:12.0-alpine
  environment:
    POSTGRES_USER: pg
    POSTGRES_PASSWORD: pg
    POSTGRES_DB: pg
  ports:
    - "6543"
stub:
  build: .
  links:
    - postgres
  ports:
    - "5000:5000"
